[theme]

primaryColor="#24DE84"
backgroundColor="#1D1B1A"
secondaryBackgroundColor="#333333"
textColor="#fafafa"
font="sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true


[client]
toolbarMode = "minimal"
showErrorDetails = true
showSidebarNavigation = false

[ui]
hideTopBar = true  
